name = "ISC"
uuid = "1ef99bb9-c61c-40b6-bffa-79a79a1182ef"
authors = ["Kevin-Mattheus-Moerman <kevin.moerman@gmail.com>"]
version = "0.1.0"

[deps]
Comodo = "59095408-2761-4f7a-bdc2-044e78630271"

[compat]
Comodo = "1.0.1"
