# FUNCTIONS - INP FILE - Abaqus

function Inp1_Head(; file, jobname, title, generated_by)
    println(file, "*Heading")
    println(file, "** =====================================")
    println(file, "** $title")
    println(file, "** GENERATED BY $generated_by")
    println(file, "** =====================================")

    println(file, "")
    println(file, "** Job Name : $jobname")

    println(file, "")
    println(file, "*Preprint, echo=NO, model=NO, history=NO, contact=NO")

    println(file, "")
    println(file, "**")
    println(file, "** PARTS")
    println(file, "**")
end

function Inp2_Part(; file, part_name, nodes, elements, element_type, section, material)

    println(file, "**")
    println(file, "** ====================================")
    println(file, "** PART")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "*Part, name=$part_name")
    println(file, "* Node")

    for (i, v) in enumerate(nodes)
    println(file, @sprintf("%8i, %24.16e, %24.16e, %24.16e", i, v[1], v[2], v[3]))
    end

    println(file, "*Element, type=$element_type")

    for (i, e) in enumerate(elements)
    println(file, @sprintf("%8i, %8i, %8i, %8i, %8i, %8i, %8i, %8i, %8i", i, e[1], e[2], e[3], e[4], e[5], e[6], e[7], e[8]))
    end

    println(file, "*Elset, elset=\"SET-($part_name)\", generate")
    println(file, "1,    $(length(elements)),    1")
    println(file, "** Section: $section")
    println(file, "*Solid Section, elset=\"SET-($part_name)\", material=$material")
    println(file, ",")
    println(file, "*End Part")
    println(file, "**")
end

function Inp3_1_Asem_S(; file, assembly_name = "Assembly")
    
    println(file, "**")
    println(file, "** ====================================")
    println(file, "** ASSEMBLY - START")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "** ASSEMBLY")
    println(file, "**")
    println(file, "*Assembly, name=$assembly_name")
    println(file, "**")
end

function Inp3_2_Instan(; file, instance_name, part_name,
                         translation = (0.0, 0.0, 0.0),
                         rotate = false,
                         rotation = (0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0))

    println(file, "**")
    println(file, "** ====================================")
    println(file, "** CREATE - INSTANCES")
    println(file, "** ====================================")
    println(file, "**")

    println(file, "*Instance, name=$instance_name, part=$part_name")

    println(file, join([iszero(x) ? "0." : string(x) for x in translation], ", "))

    if rotate
        println(file, join([iszero(x) ? "0." : string(x) for x in rotation], ", "))
    end

    println(file, "*End Instance")
    println(file, "**")
end

function Inp3_3_Set_Node(; file, rp_name, node_id, x, y, z)
    
    println(file, "**")
    println(file, "** ====================================")
    println(file, "** CREATE SET - NODES")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "*Node")
    println(file, "$node_id, $x, $y, $z")
    println(file, "*Nset, nset=$rp_name")
    println(file, "$node_id")
    println(file, "**")
end

function Inp3_4_Set_Instan(; file, set_name, instance_name, set_ids, chunk_size = 8)
    
    println(file, "**")
    println(file, "** ====================================")
    println(file, "** CREATE SET - INSTANCES")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "*Nset, nset=$set_name, instance=$instance_name")

    for i in 1:chunk_size:length(set_ids)
        chunk = set_ids[i:min(i + chunk_size - 1, length(set_ids))]
        println(file, join(chunk, ", "))
    end

    println(file, "**")
end

function Inp3_5_Eq_Const(; file, name, n_terms, set_name_1, set_name_2, DOF)
    
    println(file, "**")
    println(file, "** ====================================")
    println(file, "** EQUATION CONSTRAINTS")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "**Constraint: $name")
    println(file, "*Equation")
    println(file, "$n_terms")
    println(file, "$set_name_1, $DOF, -1.")
    println(file, "$set_name_2, $DOF, +1.")
end

function Inp3_6_Tie_Const(; file, master_set, slave_set, adjust = "yes")
    master_clean = replace(master_set, "-" => "")
    slave_clean  = replace(slave_set, "-" => "")

    master_surf = "MASTER_SURF_$master_clean"
    slave_surf  = "SLAVE_SURF_$slave_clean"
    tie_name    = "Tie-$master_clean-$slave_clean"

    println(file, "**")
    println(file, "** ====================================")
    println(file, "** TIE CONSTRAINTS")
    println(file, "** ====================================")
    println(file, "**")
    
    println(file, "*Surface, type=NODE, name=$master_surf")
    println(file, "$master_set,")

    println(file, "*Surface, type=NODE, name=$slave_surf")
    println(file, "$slave_set,")

    println(file, "** Constraint: $tie_name")
    println(file, "*Tie, name=$tie_name, adjust=$adjust")
    println(file, "$slave_surf, $master_surf")
end

function Inp3_7_Assembly_End(; file)

    println(file, "**")
    println(file, "** ====================================")
    println(file, "** ASSEMBLY - END")
    println(file, "** ====================================")
    println(file, "**")

    println(file, "*End Assembly")
    println(file, "**")
end

function Inp5_1_Inter_Props(; file, property_name="Fric", friction_coeff=0.3, slip_tol=0.005, behaviour="penalty")
    println(file, "**")
    println(file, "** ================================")
    println(file, "** INTERACTION PROPERTIES")
    println(file, "** ================================")
    println(file, "**")

    println(file, "*Surface Interaction, name=$property_name")
    println(file, "1.,")
    println(file, "*Friction, slip tolerance=$slip_tol")
    println(file, "$friction_coeff,")
    println(file, "*Surface Behavior, $behaviour")
    println(file, "**")
end

function Inp6_1_BCs_Head(; file)
    
    println(file, "**")
    println(file, "** ================================")
    println(file, "** BOUNDARY CONDITIONS")
    println(file, "** ================================")
    println(file, "**")

    
end

function Inp6_2_BCs(; file, name, set_name, dof, value = 0.0)
    println(file, "** Name: $name Type: Displacement/Rotation")
    println(file, "*Boundary")
    println(file, "$set_name, $dof, $dof, $value")
end

function Inp7_1_Inter_Genr(; file, interaction_name = "General Contact", property_name = "Fric")
    
    println(file, "**")
    println(file, "** ================================")
    println(file, "** GENERAL CONTACT")
    println(file, "** ================================")
    println(file, "**")

    
    println(file, "** INTERACTIONS")
    println(file, "**")
    println(file, "** Interaction: $interaction_name")
    println(file, "*Contact")
    println(file, "*Contact Inclusions, ALL EXTERIOR")
    println(file, "*Contact Property Assignment")
    println(file, ",  , $property_name")
    println(file, "** ----------------------------------------------------------------")
end

function Inp8_1_Step_Creat(; file, step_name = "Apply Load", nlgeom = "YES", inc = 1000, stabilize_factor = 0.0002, allsd_tol = 0, continue_flag = "NO", initial_inc = 0.001, total_time = 1.0, min_inc = 1e-5, max_inc = 1.0)

    println(file, "**")
    println(file, "** ================================")
    println(file, "** STEP")
    println(file, "** ================================")
    println(file, "**")

    println(file, "**")
    println(file, "** STEP: $step_name")
    println(file, "**")
    println(file, "*Step, name=$step_name, nlgeom=$nlgeom, inc=$inc")
    println(file, step_name)
    println(file, "*Static, stabilize, factor=$stabilize_factor, allsdtol=$allsd_tol, continue=$continue_flag")
    println(file, "$initial_inc, $total_time, $min_inc, $max_inc")
end

function Inp9_1_Out_Req(; file, restart_frequency = 0, field_name = "F-Output-1", field_variable = "PRESELECT", history_name = "H-Output-1", history_variable = "PRESELECT")

    println(file, "**")
    println(file, "** ================================")
    println(file, "** OUTPUT REQUESTS")
    println(file, "** ================================")
    println(file, "**")

    println(file, "*Restart, write, frequency=$restart_frequency")
    println(file, "**")
    println(file, "** FIELD OUTPUT: $field_name")
    println(file, "**")
    println(file, "*Output, field, variable=$field_variable")
    println(file, "**")
    println(file, "** HISTORY OUTPUT: $history_name")
    println(file, "**")
    println(file, "*Output, history, variable=$history_variable")
    println(file, "*End Step")
end